
# Except for the secret key, none of these are actually needed; Rocket has sane
# defaults. We show all of them here explicitly for demonstrative purposes.

[default.limits]
forms = "640 kB"
json = "10 MiB"
msgpack = "20 MiB"
"file/jpg" = "50 MiB"

[default]
key = "a default app-key"
extra = false
ident = "Rocket"

[debug]
address = "0.0.0.0"
port = 8080
workers = 7
keep_alive = 0
log_level = "normal"

[release]
address = "0.0.0.0"
port = 8080
workers = 7
keep_alive = 5
log_level = "critical"
secret_key = "hPRYyVRiMyxpw5sBB1XeCMN1kFsDCqKvBi2tyrdsQk="
key = "qwertyuiop"
extra = false